-- Create User Table
create table public.users (
  id bigint generated by default as identity not null,
  uid character varying(255) not null,
  name character varying(255) not null,
  email character varying(255) not null,
  created_at timestamp without time zone not null default now(),
  updated_at timestamp without time zone null default now(),
  last_sign_in timestamp without time zone null default now(),
  constraint users_pkey primary key (id),
  constraint users_email_key unique (email),
  constraint users_uid_key unique (uid)
) TABLESPACE pg_default;

-- Create Todos Table
create table public.todos (
  id bigint generated by default as identity not null,
  user_id character varying not null,
  name character varying not null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone null,
  constraint todo_pkey primary key (id),
  constraint todo_id_key unique (id),
  constraint todo_user_id_fkey foreign KEY (user_id) references users (uid) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;